site_name: Electronic load
repo_url: https://github.com/Dominik-Workshop/electronic-load
repo_name: GitHub
docs_dir: source
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    scheme: slate
    primary: teal
    accent: lime
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css

nav:
  - Overview: index.md
  - Hardware Design: hardware-design.md
  - Software & Firmware: software.md
  - Testing & Performance: testing-performance.md
